### ISSUE TITLE
github.com/oschwald/maxminddb-golang@v1.7.1-0.20200819192241-1f1e288ee3f9: invalid version: 

### ISSUE THREAD

**Issue by laurretang** [maxmind/mmdb-from-go-blogpost#10]
As shown in the title, v1.7.1 is absent in https://github.com/oschwald/maxminddb-golang/releases.

**Comment by oschwald** [comment]
This is an indirect dependency. The `mmdbwriter` dependency depended on an unreleased commit of `maxminddb`. It should still build fine. However, we might as well update the dependencies in this repo.
