### ISSUE TITLE
Incorrect result after import from CSV file

### ISSUE THREAD

**Issue by Ketan-Desai** [maxmind/mmdb-from-go-blogpost#19]
Hi,

I have created a custom MMDB file from the 'GeoIP2-ISP-CSV_20230210.zip' file using the following code...
When I query the network address, the response does not match.

For Example, Query: 1.0.4.0/24, Response: 1.0.4.0/22. (former is from CSV, and the latter is from custom MMDB)
But querying GeoIP2-ISP.mmdb gives the correct response.

package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"log"
	"net"
	"os"

	"github.com/maxmind/mmdbwriter"
	"github.com/maxmind/mmdbwriter/mmdbtype"
)

func main() {
	writer, err := mmdbwriter.New(
		mmdbwriter.Options{
			DatabaseType:            "IP",
			Description:             map[string]string{"en": "IP Database"},
			IncludeReservedNetworks: true,
			Languages:               []string{"en"},
			RecordSize:              24,
		},
	)

	if err != nil {
		log.Fatal(err)
	}

	for _, file := range []string{"GeoIP2-ISP-Blocks-IPv4.csv""} {
		fh, err := os.Open(file)

		if err != nil {
			log.Fatal(err)
		}

		r := csv.NewReader(fh)

		r.Read() // skip header

		for {
			row, err := r.Read()

			if err == io.EOF {
				break
			}
			if err != nil {
				log.Fatal(err)
			}

			if len(row) != 7 {
				log.Fatalf("unexpected CSV rows: %v", row)
			}

			_, network, err := net.ParseCIDR(row[0])

			if err != nil {
				log.Fatal(err)
			}

			if row[2] != "" {
				record := mmdbtype.Map{}
				record["org"] = mmdbtype.String(row[2])

				err = writer.Insert(network, record)

				if err != nil {
					log.Fatal(err)
				}
			}
		}
	}

	fh, err := os.Create("IP.db")

	if err != nil {
		log.Fatal(err)
	}

	_, err = writer.WriteTo(fh)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Success!")
}

**Comment by oschwald** [comment]
From your description of the problem, I think this is the expected behavior. The database writer merges two adjacent nodes in the tree if their values are the same. Given that you are creating a database with only the organization data, it is expected that some networks would get merged together.
