### ISSUE TITLE
add new localipaddress

### ISSUE THREAD

**Issue by j-nanaji** [maxmind/mmdb-from-go-blogpost#2]
Hi,

Please help to provide one use case, how to add new ipaddress range in to GeoLite2-City.mmdb.

ex: private ipaddress like 10.200.11.0-10.200.11.20 -- want to add these ipaddress range under singapore region.

**Comment by nchelluri** [comment]
Hi, I think you're probably running into an issue with the private IP range. If you set the `IncludeReservedNetworks` option to `true`, it should work.

Here is some sample code to do what you've asked:


```
package main

import (
	"log"
	"net"
	"os"

	"github.com/maxmind/mmdbwriter"
	"github.com/maxmind/mmdbwriter/inserter"
	"github.com/maxmind/mmdbwriter/mmdbtype"
)

func main() {
	// Load the database we wish to enrich.
	writer, err := mmdbwriter.Load("GeoLite2-City.mmdb", mmdbwriter.Options{IncludeReservedNetworks: true})
	if err != nil {
		log.Fatal(err)
	}

	// Define and insert the new data.
	data := mmdbtype.Map{
		"country": mmdbtype.Map{
			"geoname_id": mmdbtype.Uint32(1880251),
			"iso_code":   mmdbtype.String("SG"),
			"names": mmdbtype.Map{
				"en": mmdbtype.String("Singapore"),
			},
		},
	}
	_, network1, err := net.ParseCIDR("10.200.11.0/28")
	if err != nil {
		log.Fatal(err)
	}
	if err := writer.InsertFunc(network1, inserter.TopLevelMergeWith(data)); err != nil {
		log.Fatal(err)
	}

	_, network2, err := net.ParseCIDR("10.200.11.16/30")
	if err != nil {
		log.Fatal(err)
	}
	if err := writer.InsertFunc(network2, inserter.TopLevelMergeWith(data)); err != nil {
		log.Fatal(err)
	}

	_, network3, err := net.ParseCIDR("10.200.11.20/32")
	if err != nil {
		log.Fatal(err)
	}
	if err := writer.InsertFunc(network3, inserter.TopLevelMergeWith(data)); err != nil {
		log.Fatal(err)
	}

	// Write the newly enriched DB to the filesystem.
	fh, err := os.Create("GeoLite2-City-with-Reserved-SG-Data.mmdb")
	if err != nil {
		log.Fatal(err)
	}
	_, err = writer.WriteTo(fh)
	if err != nil {
		log.Fatal(err)
	}
}
```

I adapted the example from the blogpost by changing the data we use to the data you supplied and used a CIDR calculator to determine the ranges for 10.200.11.0 - 10.200.11.20, and finally used the `IncludeReservedNetworks` as discussed above.

**Comment by j-nanaji** [comment]
Hi Narsimham,

Thanks a lot for the code. It is working fine as expected. how file sizes
are different?. the original file is 60MB and the newly generated file
is size instead supposed to be bigger than original file.

[image: image.png]

Thanks & Best Regards
Nanaji

**Comment by nchelluri** [comment]
Hi Nanaji, glad it worked out for you. The source database was originally generated by https://github.com/maxmind/MaxMind-DB-Reader-perl and the implementation is slightly different than using this library. It is safe to ignore the difference in file size, as it is an implementation detail. Databases generated with this library will be slightly smaller than those generated with the Perl one, generally, due to a difference in the logic on when to use a pointer.

**Comment by j-nanaji** [comment]
Hi Narsimham,

Thanks a lot for the details. Really appreciate it.

Best Regards
Nanaji
