### ISSUE TITLE
Splunk can't load the updated mmdb file

### ISSUE THREAD

**Issue by DVRusak** [maxmind/mmdb-from-go-blogpost#23]
In general, the situation is this: I use mmdb to determine the ip location in traffic in Splunk using the module | iplocation.

When you load a regular mmdb without changes, it loads well.
![well](https://github.com/maxmind/mmdb-from-go-blogpost/assets/118663754/491f809c-4b71-4161-bf89-0f49c96a2d66)

When you load an mmdb file processed by the library, it’s a completely different bad outcome.
![bad](https://github.com/maxmind/mmdb-from-go-blogpost/assets/118663754/8039516d-baf7-4cea-8281-615a5d08c16b)

Those. In general, I simply took and rewrote mmdb without making changes, and still Splunk did not want to accept it.

Question: what does the library do that makes Splunk stop accepting the file??? (If you look at the metadata, only build_epoch changes. The file size does not change.)

Code for just rewrite mmdb:
package main

import (
	"log"
	"os"

	"github.com/maxmind/mmdbwriter"
)

func main() {

	// Load the database we wish to enrich.
	var path_to_db string
	path_to_db = "test/GeoLite2-City.mmdb"

	writer, err := mmdbwriter.Load(path_to_db, mmdbwriter.Options{})
	if err != nil {
		log.Fatal(err)
	}

	
	// Write the newly enriched DB to the filesystem.
	fh, err := os.Create("test/GeoLite2-City1.mmdb")
	if err != nil {
		log.Fatal(err)
	}
	_, err = writer.WriteTo(fh)
	if err != nil {
		log.Fatal(err)
	}
}

**Comment by DVRusak** [comment]
If you look in the WinMerge program, the differences are in two memes in one line
![image](https://github.com/maxmind/mmdb-from-go-blogpost/assets/118663754/74fe9dc7-56c7-4918-980d-ba1c9cc8d471)

**Comment by oschwald** [comment]
The official MMDB is also written with this library. Does Splunk provide a particular error?

**Comment by DVRusak** [comment]
There may be some additional information in the logs, but you need to know where to look

![image](https://github.com/maxmind/mmdb-from-go-blogpost/assets/118663754/1bf0e5af-b225-43b6-bbf1-b5bc8e38cc20)

The error in the screenshot occurs if the raw mmdb is replaced in the Splunk files with a custom version.

Accordingly, if the replacement is made through the web console, then Splunk will not allow you to download this file

**Comment by DVRusak** [comment]
The problem was solved after manually replacing the string element " w" with "Ben" (marked in yellow in the screenshot)

Moreover, if you use lookups in python and go languages, then there will be no difference in the metadata when reading. But in the hex editor the difference is visible, and not only in build_epoch.
![image](https://github.com/maxmind/mmdb-from-go-blogpost/assets/118663754/e089ba82-a97c-4ae7-bee4-d1a31145ecf9)

Apparently Splunk cannot read the slightly different mmdb metadata structure.

![solwed](https://github.com/maxmind/mmdb-from-go-blogpost/assets/118663754/beed2396-91c2-4805-a5f6-8b1421c7aa87)

**Comment by oschwald** [comment]
I am guessing the issue is that Splunk is using an old version of `libmaxminddb` that does not correctly handle pointers in the metadata. You can disable these with the `DisableMetadataPointers` option.
