### ISSUE TITLE
show custom geoip  fields

### ISSUE THREAD

**Issue by DoTime** [maxmind/mmdb-from-go-blogpost#8]
` geoip{
   source => "client_ip"
   database => "D:\elk\conf\geoIP\go\mmdb-from-go-blogpost\GeoLite2-Country-with-Department-Data.mmdb"
   fields => ["city_name", "continent_code", "country_code2", "country_code3", "country_name", "dma_code", "ip", "latitude", "longitude", "postal_code", "region_name", "timezone","**AcmeCorp.DeptName**"]

 } 
`
How show [AcmeCorp.DeptName] in geoip with logstash  plugins??
Could you give some help??

**Comment by nchelluri** [comment]
Can you please explain in a bit more detail what the top portion of your issue is? I have not seen logstash plugins before, but I'm looking them up and can try to assist if you give me some more info.

**Comment by DoTime** [comment]
> Can you please explain in a bit more detail what the top portion of your issue is? I have not seen logstash plugins before, but I'm looking them up and can try to assist if you give me some more info.

from https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html

I want show custom geoip fields AcmeCorp.DeptName and AcmeCorp.Environments in logstash from GeoLite2-Country-with-Department-Data.mmdb, like continent_name or country_name from original GeoLite2-Country.mmdb but i don't how to do it... 

` "geoip" => {
        "continent_name" => "North America",
          "country_name" => "United States",
         "country_code2" => "US",
                    "ip" => "56.0.0.2"
    },`

**Comment by nchelluri** [comment]
Thanks; I might try and get a JRuby Docker env going so I can try running this and poking at it, but before then, can you try not setting `fields` at all on the filter? It should include every field in that case:

> By default, all geoip fields are included in the event.

- from https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html#plugins-filters-geoip-fields

Perhaps you have already done this, but I'm wondering if it's going by some other name for some reason.

**Comment by DoTime** [comment]
> Thanks; I might try and get a JRuby Docker env going so I can try running this and poking at it, but before then, can you try not setting `fields` at all on the filter? It should include every field in that case:
> 
> > By default, all geoip fields are included in the event.
> 
> * from https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html#plugins-filters-geoip-fields
> 
> Perhaps you have already done this, but I'm wondering if it's going by some other name for some reason.

I actually use this one and nothing else . I got error  if set `fields`  with "AcmeCorp.DeptName".
Thank you~

` geoip{
   source => "client_ip"
   database => "D:\ProWork\elk7.13.3\conf\geoIP\go\mmdb-from-go-blogpost\GeoLite2-Country-with-Department-Data.mmdb"
 } `

**Comment by nchelluri** [comment]
To clarify, are you running into issues now, without the `fields` set at all? Or is it working as expected?

**Comment by nchelluri** [comment]
Ah, can you post the error you get when you specify the field name?

**Comment by DoTime** [comment]
> To clarify, are you running into issues now, without the `fields` set at all? Or is it working as expected?

It's not working when only set source&database , not found **AcmeCorp.DeptName**  in the last result.

input data: 
`56.0.0.2 GET /login00.html 11125 0.88
56.0.0.3 GET /login00.html 11125 0.33`

logstash conf: 
`input {
 beats {
    port => 5044
  }

filter {
 grok {
   match => {
   "message" => "%{IPV4:client_ip} %{WORD:method} %{URIPATHPARAM:request} %{NUMBER:bytes} %{NUMBER:duration}"
  } 
 }
 
 geoip{
   source => "client_ip"
   database => "D:\ProWork\elk7.13.3\conf\geoIP\go\mmdb-from-go-blogpost\GeoLite2-Country-with-Department-Data.mmdb"
 } 
}

  stdout{ }

}
 
`

this is the result:

![image](https://user-images.githubusercontent.com/15666939/126494429-f486c1fd-f3d3-49b2-81f4-0b9234d2d15d.png)

**Comment by nchelluri** [comment]
Thanks; I'm going to get my environment set up and try to take a look at this; it might take me a few days as I have some other work to attend to.

**Comment by DoTime** [comment]
> Thanks; I'm going to get my environment set up and try to take a look at this; it might take me a few days as I have some other work to attend to.

I  understand , thank you~

**Comment by nchelluri** [comment]
I don't think this is going to work without someone changing the [logstash-filter-geoip](https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/src/main/java/org/logstash/filters/geoip/Fields.java) library. You'll note that the `Fields` type is an enum: it cannot take arbitrary values (https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/src/main/java/org/logstash/filters/geoip/Fields.java#L26, https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/src/main/java/org/logstash/filters/geoip/Fields.java#L110-L117).

I think that library needs to be fixed to deal with arbitrary fields and then it should work.

**Comment by nchelluri** [comment]
I will add: if you want to get that plugin running for development, https://github.com/cameronkerrnz/logstash-plugin-dev seems to work pretty well.

**Comment by DoTime** [comment]
it's useful ,  thanks you~
